### ISSUE TITLE
SQLCE 3.5 Support

### ISSUE THREAD

**Issue by rowanmiller** [ErikEJ/EntityFramework.SqlServerCompact#122]
Hey Erik,

We had a customer asking about SQLCE 3.5 support in EF7. I just wanted to get your thoughts on whether this is something you might tackle?

**Comment by ErikEJ** [comment]
Yes, I plan to do that... Just like I did with the EF6 provider! :smiley: Maybe the customer could help with testing and other feedback?

**Comment by rowanmiller** [comment]
Great. I'll let them know.

**Comment by ErikEJ** [comment]
@rowanmiller 3.5 SP2 Package now available, and Wiki has been updated: https://github.com/ErikEJ/EntityFramework.SqlServerCompact/wiki/Using-EF7-with-SQL-Server-Compact-in-Traditional-.NET-Applications

**Comment by rowanmiller** [comment]
Sweet, quick turnaround!
