### ISSUE TITLE
Can not add DefaultValue for non-reference types

### ISSUE THREAD

**Issue by HildarTheDorf** [ErikEJ/EntityFramework.SqlServerCompact#288]
Attempting to call the extensions in SqlCePropertyBuilderExtensions fails if TProperty is a value type such as Guid or it's nullable equivalent. This is different to the SqlServer version of these functions which do allow value types.

In addition, I tried to fix this myself but I can not seem to build the code? I can not seem to find any of the rc2 nuget packages this depends on.

**Comment by ErikEJ** [comment]
Could you provide a sample that explains this issue? To build, restore nuget packages.

**Comment by ErikEJ** [comment]
I can see the issue now, the extension is simply not implemented.

**Comment by ErikEJ** [comment]
This is not yet fixed, see https://github.com/aspnet/EntityFramework/issues/4469 - need to impelemt this fix!
