### ISSUE TITLE
Nuget issues

### ISSUE THREAD

**Issue by nicolasr75** [ErikEJ/EntityFramework.SqlServerCompact#297]
Sorry, I have again issues installing it. I tried a new WPF project and tried to install EntityFramework.SqlServerCompact40.7.0.0-rc2-413  but it can't resolve EntityFramework.Relational (= 7.0.0-rc2-16751). My AspnetVNext feed is showing only 16649 as the newest pre-release. What am I doing wrong? Do I have the wrong feed? The feed I'm using is https://www.myget.org/F/aspnetvnext/api/v3/index.json
Thanks for your help,
Nicolas

**Comment by ErikEJ** [comment]
Try this feed: https://www.myget.org/F/aspnetcidev/api/v3/index.json

**Comment by nicolasr75** [comment]
Thanks, at first it looks better but then fails with
"The referenced component 'Microsoft.Extensions.Logging' could not be found."	
Is this maybe also an issue of target framework? I tried 4.6.1 but have set it to 4.5.1 now, both don't work.

**Comment by ErikEJ** [comment]
Remove all nuget packages from your references, and delete packages.config, and try again...

**Comment by nicolasr75** [comment]
Awesome! That did it. Thanks so much!

**Comment by ErikEJ** [comment]
It is a well known issue: https://github.com/aspnet/EntityFramework/issues/4395
