### ISSUE TITLE
Respond to Migrations changes (maybe)

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EntityFramework.SqlServerCompact#30]
https://github.com/aspnet/EntityFramework/pull/2163

**Comment by bricelam** [comment]
Shouldn't be any changes required for providers here. (Other than maybe a test or two)

**Comment by ErikEJ** [comment]
@bricelam  Thanks, I just noticed a change to a test, yes, Just making a note to update when I manage to pull in a newer nightly build https://github.com/aspnet/EntityFramework/issues/2152
