### ISSUE TITLE
Type must be a reference type in order to use it as a parameter T

### ISSUE THREAD

**Issue by samaravathi** [ErikEJ/EntityFramework.SqlServerCompact#318]
I get the error stated in the subject line when setting default value for a DateTime property.
Can you please help.

This is what I'm doing, as per the documentation at http://ef.readthedocs.org/en/latest/modeling/relational/default-values.html

class SomeClass
{
       public DateTime Created{get;set;} <--Value type
}
class SomeContext:DbContext
{
        public override void OnModelCreating()
        {
                 modelBuilder.Entity<SomeClass>()
                .Property(b => b.Created)
                .HasSqlCeDefaultValueSql("getdate()");   <-----Error here
        }
}

**Comment by ErikEJ** [comment]
Which version - I fixed a bug releated to this, that will be in RC2.

**Comment by samaravathi** [comment]
Its SqlServerCompact 4.0
runtime version - v4.0.30319
Version - 7.0.0.0

**Comment by ErikEJ** [comment]
Which package version exactly? 7.0.0 has not been released....

**Comment by samaravathi** [comment]
Hi Erik

Here is the packages.config :

<packages>
  <package id="EntityFramework.Commands" version="7.0.0-rc1-final" targetFramework="net451" />
  <package id="EntityFramework.Core" version="7.0.0-rc1-final" targetFramework="net451" />
  <package id="EntityFramework.Relational" version="7.0.0-rc1-final" targetFramework="net451" />
  <package id="EntityFramework.Relational.Design" version="7.0.0-rc1-final" targetFramework="net451" />
  **<package id="EntityFramework.SqlServerCompact40" version="7.0.0-rc1-final" targetFramework="net451" />**
  <package id="Ix-Async" version="1.2.5" targetFramework="net451" />
  <package id="Microsoft.Extensions.Caching.Abstractions" version="1.0.0-rc1-final" targetFramework="net451" />
  <package id="Microsoft.Extensions.Caching.Memory" version="1.0.0-rc1-final" targetFramework="net451" />
  <package id="Microsoft.Extensions.Configuration" version="1.0.0-rc1-final" targetFramework="net451" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="1.0.0-rc1-final" targetFramework="net451" />
  <package id="Microsoft.Extensions.Configuration.Binder" version="1.0.0-rc1-final" targetFramework="net451" />
  <package id="Microsoft.Extensions.DependencyInjection" version="1.0.0-rc1-final" targetFramework="net451" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="1.0.0-rc1-final" targetFramework="net451" />
  <package id="Microsoft.Extensions.Logging" version="1.0.0-rc1-final" targetFramework="net451" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="1.0.0-rc1-final" targetFramework="net451" />
  <package id="Microsoft.Extensions.OptionsModel" version="1.0.0-rc1-final" targetFramework="net451" />
  <package id="Microsoft.Extensions.Primitives" version="1.0.0-rc1-final" targetFramework="net451" />
  <package id="Microsoft.SqlServer.Compact" version="4.0.8876.1" targetFramework="net451" />
  <package id="Remotion.Linq" version="2.0.1" targetFramework="net451" />
  <package id="System.Collections.Immutable" version="1.1.36" targetFramework="net451" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.0.0-beta-23516" targetFramework="net451" />
</packages>

Thanks a lot

**Comment by ErikEJ** [comment]
The issue you report is fixed in the current codebase
