### ISSUE TITLE
IndexBuilder.IsUnique behaves differently than for SqlServer for nullable properties

### ISSUE THREAD

**Issue by vmsgsp** [ErikEJ/EntityFramework.SqlServerCompact#359]
When a property is nullable, SqlServerCompact does not generate a unique index when IndexBuilder.IsUnique is called on that property (it only creates a non-unique index).
On the other hand, for SqlServer Entity Framework Core 1.0 does generate a UNIQUE index (also for nullable properties).
Why this different behavior?
In SqlServerCompact 7.0.0-rc1-final this still worked correctly (= consistently with SqlServer = UNIQUE index).
Source code example:
` 
public class Blog    {
        public int BlogId { get; set; }
        public string Url { get; set; }
    }
modelBuilder.Entity<Blog>()

              .HasIndex(b => b.Url)
              .IsUnique();
`

Yields the following incorrect, non-unique index: 
CREATE INDEX [IX_Blogs_Url] ON [Blogs] ([Url] ASC);

However if you add the IsRequired() to the Url property, the index will be UNIQUE:
`
modelBuilder.Entity<Blog>().
              Property(b => b.Url).IsRequired();

modelBuilder.Entity<Blog>()
              .HasIndex(b => b.Url)
              .IsUnique();``

=> Yields the correct UNIQUE index: 
CREATE UNIQUE INDEX [IX_Blogs_Url] ON [Blogs] ([Url] ASC);

**Comment by ErikEJ** [comment]
The reasoning behind this is here: https://github.com/aspnet/EntityFramework/pull/5631 - hope it makes sense?

**Comment by vmsgsp** [comment]
@ErikEJ: Thanks for your quick reply! But I am still unsure whether I really understood the reaonsing behind.

 aspnet/EntityFramework#5631 is about foreign keys. My example is on a regular column. And what irritates most is the different behavior for SqlServer and SqlCE.
But in aspnet/EntityFramework#5631 bricelam says "It might also be worth doing for all nullable columns "

=> So do you want to tell me that with a future (which?) release of EntityFramework Core the behavior will be in sync both for SqlServer and SqlCE (that is: generate non-unique index for nullable columns)?

**Comment by ErikEJ** [comment]
I think I should remove the lines here - that should give you back your desired behaviour:

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Migrations/SqlCeMigrationsSqlGenerator.cs#L57

**Comment by vmsgsp** [comment]
Thanks. It is good to hear that the SqlCe will behave the same way as for SQL server. For which release do you plan this fix? When will it be available?

**Comment by ErikEJ** [comment]
I Think for 1.0.0 and "soon"

**Comment by ErikEJ** [comment]
Also, please be aware that Unique on a nullable column means different things in the SQL Server vs SQL Server Compact context, so the behaviour will NEVER be the same!

Unique on a nullable column for SQL Server means: 
Multiple rows with NULL values and unique non-null values.
(This is implemented by way of a filtered index, a feature not available on SQL Sever Compact)

Unique on SQL Server Compact means:
A single row with the value NULL, and unique non-null values.

**Comment by vmsgsp** [comment]
Thanks for informing me about that continuing difference. 
Maybe it is worth to be mentioned in an overview like:
https://technet.microsoft.com/en-us/library/bb896140(v=sql.110).aspx

**Comment by ErikEJ** [comment]
I have no access to update that page - I might mention it in the wiki here.

**Comment by vmsgsp** [comment]
Also fine for me :-)

**Comment by ErikEJ** [comment]
I have updated https://github.com/ErikEJ/EntityFramework.SqlServerCompact/wiki/Limitations - let me know if you have any comments (or do a PR)

**Comment by ErikEJ** [comment]
@vmsgsp Did the fix work for you?

**Comment by vmsgsp** [comment]
Tested with EntityFrameworkCore.SqlServerCompact40.1.0.0.3.
It works as expected.
Thank you!
