### ISSUE TITLE
Question: "may also work under ASP.NET Core 1.0 when using the full .NET runtime"?

### ISSUE THREAD

**Issue by UlyssesWu** [ErikEJ/EntityFramework.SqlServerCompact#361]
I have a website built with ASP.NET Core 1.0. And I currently deployed it on Windows Server with full .NET 4.5 installed. The readme.md said it "may also work under ASP.NET Core 1.0 when using the full .NET runtime". Does that means I can use this provider? 

But when I get it from nuget it says:

>     Package EntityFrameworkCore.SqlServerCompact40 1.0.0.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package EntityFrameworkCore.SqlServerCompact40 1.0.0.3 supports: net451 (.NETFramework,Version=v4.5.1)
>     One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by ErikEJ** [comment]
Your project must target the full .net runtime, not .net core

**Comment by UlyssesWu** [comment]
Thanks. 
So what does "work under ASP.NET Core 1.0" means actually? 
Is it possible to switch to full .NET runtime for a .NET core app?

**Comment by ErikEJ** [comment]
Not for a .Net core app, but for a asp.net core app, yes https://docs.asp.net/en/latest/data/entity-framework-6.html (the project.json changes only)

**Comment by ErikEJ** [comment]
Let me know how it goes!

**Comment by UlyssesWu** [comment]
Yes, I changed the framework section like this:
```
    "frameworks": {
        "net451": {}
        //"netcoreapp1.0": {
        //    "imports": [
        //        "dotnet5.6",
        //        "portable-net45+win8"
        //    ]
        //}
    },
```
And then commented the `Microsoft.NETCore.App` in dependencies section. And the nuget worked.
But in fact there are still some problem: Can not start debug from VS. Got a "Can not start D:\xx\xx.exe. Access denied." error. Still it can compile and the output .exe works.
I will update my code tomorrow to see if the provider can work. Thanks a lot!

**Comment by UlyssesWu** [comment]
OK, works well. And the debug issue disappeared somehow (after my reboot?).
problems encountered:
1. #271  
Since `LockoutEnd` in Indentity is nullable DateTimeOffset now (aspnet/Identity#248), I need to ignore it in ApplicationDbContext.cs:
`builder.Entity<ApplicationUser>().Ignore(x => x.LockoutEnd);`
2. DateTime overflow
Set default value to `(DateTime) SqlDateTime.MinValue` for all models.
3. System.InvalidOperationException: No mapping to a relational type can be found for the CLR type 'Microsoft.EntityFrameworkCore.Metadata.Internal.Property' 
Remove all migrations before.

Finally I find it hard to migrate data from the sqlite database to sqlce. So I continue to use sqlite. But at least I have learned these things. Thanks again.
