### ISSUE TITLE
Index renaming not supported in SQLCE

### ISSUE THREAD

**Issue by intexx** [ErikEJ/EntityFramework.SqlServerCompact#386]
From the [old EF6 issues list](https://github.com/aspnet/EntityFramework6/issues/149):

> The `RenameIndex()` method returns this error when migrating with SQLCE: 
>
> _"Direct index renaming is not supported by SQL Server Compact. To rename an index in SQL Server Compact, you will need to recreate it."_ 
>
> Instead, `DropIndex()` and then `CreateIndex()` should be called. It's possible to manually edit the migration accordingly, prior to updating, but this is tedious and error-prone.

Is this still a problem under the new EF Core architecture?

**Comment by ErikEJ** [comment]
Yes it is:
https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/src/Provider40/Migrations/SqlCeMigrationsSqlGenerator.cs#L207

**Comment by intexx** [comment]
Right, I saw that.

But previously, as I recall, you stated that not enough information was passed in the parameters to do a `DropIndex()` and `CreateIndex()`.

Has this situation improved?

**Comment by ErikEJ** [comment]
Maybe, I made this attempt, but for some reason backed off again:

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/commit/2132d3565be1af46430d8267db8d1f098bcdacfe

**Comment by intexx** [comment]
Just checking in...  anything I can do to help?

That change you made looks like it should work.

**Comment by ErikEJ** [comment]
Having a sample project with a migration with index rename requirement would be great 😊

**Comment by intexx** [comment]
You've got it. VB OK?

**Comment by ErikEJ** [comment]
Sure, vb is ok. You mean I already have an EF Core sample project?

**Comment by intexx** [comment]
Oops...  :-)

No, that's only a figure of speech. Something like "it's on the way" or "just ask and it's yours."

**Comment by ErikEJ** [comment]
OK - can I have it, please?
