### ISSUE TITLE
 Handle GO and (Backslash) utilities statements

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EntityFramework.SqlServerCompact#422]
https://github.com/aspnet/EntityFramework/pull/7760

**Comment by ErikEJ** [comment]
@bricelam SQL CE does not support batching of statements, so I am assuming this is not relevant?

**Comment by bricelam** [comment]
Our main motivation was to handle `*.sql` files with these statements in them. You'd know best if this is common on SQL CE.
