### ISSUE TITLE
Will be this awesome project updated to NET Standard like EFSqlite?

### ISSUE THREAD

**Issue by juanpaexpedite** [ErikEJ/EntityFramework.SqlServerCompact#424]
This was one of my first database platforms I used in mobile projects, and it has great performance, contains password protection and is Sql Server compatible for explorers and more.

So I do not really understand why it did not advance to the new standards (NET Standard) instead of the SQLite, because SQLite needs (in UWP) to be in an specific folder (storage folder), it does not support password out of the box and both are really important issues that any database should have, so... What are the plans for this amazing project?

Thank you

**Comment by ErikEJ** [comment]
Unfortunately, the SQL Compact engine is made in unmanaged code (C/C++) and very closely tied to a number of Win32 features, that are not available on other platforms (including UWP)
