### ISSUE TITLE
Run under the .NET Core runtime

### ISSUE THREAD

**Issue by AlastairSchouten** [ErikEJ/EntityFramework.SqlServerCompact#460]
The ReadMe states that [the EntityFramework.SqlServerCompact] "does not work under the .NET Core runtime". This seems a bit strange to me. Are there any plans for add such support.

By way of context I am involved in the early stages of developing an application that will run in a browser and run (disconnected if needed) on the desktop using Electron, with the client side being written using Angular 4 and the server side in .NET Core C#. The desktop application needs to occasionally synchronise with a server side database.  

Thanks

**Comment by ErikEJ** [comment]
It is not possible to get .NET Core support, as the SQL Compact engine (created in unmanaged C code) is closely tied to the Windows platform. Your best bet is probably SQLite, although it has many limitations compared with SQL Compact

**Comment by AlastairSchouten** [comment]
Thanks for the prompt response.
