### ISSUE TITLE
DbContextOptionsBuilder' does not contain a definition for 'UseSqlite' and no extension method 'UseSqlite' accepting a first argument of type 'DbContextOptionsBuilder'

### ISSUE THREAD

**Issue by NTDThanh** [ErikEJ/EntityFramework.SqlServerCompact#488]
Hi ErikEJ. I create UWP app with Visual Studio 2017 and use sql server compact/sqlite toolbox to generate EF Core Model from chinook.db . I encountered a problem in ChinookContext.cs
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
          optionsBuilder.**UseSqlite**(@"data source=D:\Data\chinook.db");
        }
Erorr: DbContextOptionsBuilder' does not contain a definition for 'UseSqlite' and no extension method 'UseSqlite' accepting a first argument of type 'DbContextOptionsBuilder'.
In my Project:
Microsoft.EntityFrameworkCore v1.1.1
Microsoft.EntityFrameworkCore.Relational   v1.1.1
Microsoft.NETCore.UniversalWindowsPlatform  v5.3.4
Microsoft.EntityFrameworkCore.Tools    v1.1.1

**Comment by ErikEJ** [comment]
You seem to be missing: Microsoft.EntityFrameworkCore.Sqlite

**Comment by NTDThanh** [comment]
Thank for help. I Installed  Microsoft.EntityFrameworkCore.Sqlite v2.0.0 and receive same problem. Then I try with Microsoft.EntityFrameworkCore.Sqlite v1.1.2 it work fine. Then I try get data from chinook.db with the following code in MainPage 
public sealed partial class MainPage : Page
    {
        List<Albums> ab = new List<Albums>();
        ChinookContext db = new ChinookContext();
        public MainPage()
        {
            this.InitializeComponent();
            ab = db.Albums.Select(x => new Albums { AlbumId = x.AlbumId, Artist = x.Artist, ArtistId = x.ArtistId, Title = x.Title, Tracks = x.Tracks }).ToList();
        }
    }
But it not success: 
Erorr: Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 14: 'unable to open database file'.'
I do not know what causes this issue to look forward to your help !

**Comment by ErikEJ** [comment]
You need to set the connection string and include the database file with your project, and possibly copy it to a writeable location after deployment - http://erikej.blogspot.dk/2012/08/getting-started-with-sqlite-in-windows.html
