### ISSUE TITLE
Entity Framework Core 1.1 Provider Truncates Image Length

### ISSUE THREAD

**Issue by eboyle1017** [ErikEJ/EntityFramework.SqlServerCompact#496]
I see that this issue was addressed in this old article about EF 4.1 http://erikej.blogspot.com/2011/04/saving-images-to-sql-server-compact.html

However, this doesn't seem to solve the problem in EF Core 1.0/1.1. I am generating a SQL CE database using EF Core code first approach, and several of my columns must store images. However, the issue is that when the image is stored, it only writes the first 8000 bytes to the database, despite allocating the full file size. So the resulting image only shows a sliver of the top 8000 bytes worth of pixels, and then empty data for the rest of the column.

This is an example of the object code I'm using:

```
public class ResourceStorage
{
        public long Id { get; set; }

        public string Tag { get; set; }

        [Column(TypeName = "image")]
        public byte[] Content { get; set; }

        public string ContentType { get; set; }

        public long Size { get; set; }
}
```

Where content is a byte array that is expected to be very large. If I don't specify TypeName = "image" it will generate a schema using VarBinary(8000). However, with this code, it generates a migration script that looks like this:

```
migrationBuilder.CreateTable(
                name: "ResourceStorage",
                columns: table => new
                {
                    Id = table.Column<long>(nullable: false)
                        .Annotation("SqlCe:ValueGeneration", "True"),
                    Content = table.Column<byte[]>(type: "image", nullable: true),
                    ContentType = table.Column<string>(nullable: true),
                    Size = table.Column<long>(nullable: false),
                    Tag = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ResourceStorage", x => x.Id);
                });
```

And in the resulting SDF file it has a schema of this:

```
CREATE TABLE [ResourceStorage]
(
   [Id] BIGINT NOT NULL IDENTITY (1,1),
   [Content] IMAGE,
   [ContentType] NVARCHAR(4000),
   [Size] BIGINT NOT NULL,
   [Tag] NVARCHAR(4000)
);
```

In the code definition I've tried using various Annotation Attributes such as `[MaxLength]`, `[MaxLength(1073741823)`, and removing the Column[TypeName bit altogether. But nothing fixes this issue for me. Everything else with the SQL CE database works just fine, in fact the application continues to run in this state, but all images appear in complete. It is not even throwing any exceptions about length violations.

Is this a limitation of EF Core? Or is it something that can be fixed at the provider level? Or better yet, is there a specific workaround for this? I am still stuck using EF Core 1.1.2 in my application, so I have not had the chance to try this in EF Core 2.0. Upgrading my application to 2.0 may not be an option at this point in time.

**Comment by ErikEJ** [comment]
Hi Sean, using the SQL CE 1.1 provider, I am unable to reproduce your issue running the code below, can you change it in order to reproduce your issue?

```csharp

using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using Xunit;

namespace Microsoft.EntityFrameworkCore.Specification.Tests
{
    public class BasicEndToEndScenarioForNoIdentity
    {
        [Fact]
        public void Can_run_end_to_end_scenario()
        {
            using (var db = new BloggingContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();
                var logo = File.ReadAllBytes("EFCore.png");
                var logoSize = logo.Length;
                db.Blogs.Add(new Blog { Id = 99, Url = "http://erikej.blogspot.com", Logo = logo });
                db.SaveChanges();

                var blogs = db.Blogs.ToList();

                Assert.Equal(blogs.Count, 1);
                Assert.Equal(blogs[0].Url, "http://erikej.blogspot.com");
                Assert.Equal(blogs[0].Id, 99);
                Assert.Equal(logoSize, blogs[0].Logo.Length);
            }
        }

        private class BloggingContext : DbContext
        {
            public DbSet<Blog> Blogs { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlCe(@"Data Source=BloggingNoIdentity.sdf");
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                base.OnModelCreating(modelBuilder);
                modelBuilder.Entity<Blog>()
                    .Property(e => e.Id)
                    .ValueGeneratedNever();
            }
        }

        private class Blog
        {
            public int Id { get; set; }
            public string Url { get; set; }

            [Column(TypeName = "image")]
            public byte[] Logo { get; set; }
        }
    }
}

```

**Comment by ErikEJ** [comment]
Adding the test image!
![efcore](https://user-images.githubusercontent.com/4169187/30237902-646aabf2-953c-11e7-8a41-8170b4b8bd6c.png)

**Comment by eboyle1017** [comment]
I ran your test code and it passes all the tests given, including checking the length. It allocates the full size of the image in the database, however, the image itself is still stopping after 8000 bytes. Take a look at what is actually stored inside the sdf file after running this test.

![capture](https://user-images.githubusercontent.com/24398689/30289282-7d744c20-96e0-11e7-9f54-fa1f9acc5592.PNG)

I ran the test using EntityFrameworkCore.SqlServerCompact40.  Do you see the same results when viewing the resulting image in the sdf file?

**Comment by ErikEJ** [comment]
Please share the sdf file!

**Comment by eboyle1017** [comment]
[BloggingNoIdentity.zip](https://github.com/ErikEJ/EntityFramework.SqlServerCompact/files/1293634/BloggingNoIdentity.zip)

Sure thing.

**Comment by ErikEJ** [comment]
Thanks, bug confirmed :-( - good catch! I will look into a fix!

**Comment by eboyle1017** [comment]
Let me know if you need anything else, I would definitely like to see this bug squashed! Switching to your provider would save me a ton of headache, but without working images, it's not possible.

**Comment by ErikEJ** [comment]
Hi, I have updated the test to prove that no data loss occurs:
https://github.com/ErikEJ/EntityFramework.SqlServerCompact/blob/master/test/EntityFramework.SqlServerCompact.FunctionalTests/BasicEndToEndScenarioForNoIdentity.cs#L29

The issue you are facing is a display issue in CompactView (also present in my SQLite Toolbox)

**Comment by eboyle1017** [comment]
Interesting, because the same display issue that was apparently in CompactView was also the exact same way it was displaying in my software after pulling it from the database. I was trying to replace our current SQLite database with SQL CE, using EF Core. I loaded up your DLL and then images started doing this. The only change to the schema was converting blobs to images. When we used SQLite in EF Core previously, our images displayed correctly.

Is there a problem with the way the data is being read which causes this bug? I see that the bytes come out correctly, but the resulting image is still not coming out correctly. I will investigate this further to find out the point of failure in my application, and get back with you.

**Comment by ErikEJ** [comment]
I will improve the test by saving the retrieved image to disk in order to invrstigate

**Comment by eboyle1017** [comment]
Instantiating a new context before reading the result seems to demonstrate the error in your unit test.

**Comment by ErikEJ** [comment]
OK, so this is a bug in 1.1 - what is preventing you from using 2.0 (where I have demonstrated that the bug does not exist) ?

**Comment by eboyle1017** [comment]
Our application has been using 1.0/1.1 and I'm not sure if upgrading to 2.0 would be feasible currently. It would require significant changes for our application. It's something that's been considered ever since 2.0 was released, but this should accelerate that effort. Staying with 1.1 would certainly be the least costly solution, but if it cannot be fixed then a 2.0 upgrade may be necessary.

**Comment by ErikEJ** [comment]
I think I have located the bug, and will investigate a worksround or fix

**Comment by ErikEJ** [comment]
I found a workaround: 

```
modelBuilder.Entity<Blog>()
                    .Property(e => e.Logo)
                    .HasMaxLength(-1);
```

**Comment by eboyle1017** [comment]
Unfortunately, this workaround doesn't appear to work in EF 1.1. Trying it on your unit test code I implemented it like this:

```
        private class BloggingContext : DbContext
        {
            public DbSet<Blog> Blogs { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlCe(@"Data Source=BloggingNoIdentity.sdf");
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                base.OnModelCreating(modelBuilder);
                modelBuilder.Entity<Blog>()
                    .Property(e => e.Id)
                    .ValueGeneratedNever();

                modelBuilder.Entity<Blog>()
                    .Property(e => e.Logo)
                    .HasMaxLength(-1);
            }
        }

        private class Blog
        {
            public int Id { get; set; }
            public string Url { get; set; }

            [MaxLength(-1)]
            [Column(TypeName = "image")]
            public byte[] Logo { get; set; }
        }
```

It changed nothing. The test still fails with a length of 8000 bytes. I tried it in my own application as well and the EF core migration tool seems to completely ignore the [MaxLength] attribute on columns that are of image type. But setting it in my Context's `OnModelCreating` using the model builder didn't seem to have any effect either. It may simply be a bug in EF Core 1.0/1.1 itself.

And in regards to upgrading to 2.0, I've spent the past day trying to upgrade my application to 2.0. There are a significant number of breaking changes and I am still trying to work out how to get EF Core 2.0 migration to work. DB Migration is the whole reason we started switching to SQL CE in the first place (instead of SQLite).

**Comment by ErikEJ** [comment]
I was FINALLY able to repro in 1.1 and have a fix for you soon!

**Comment by ErikEJ** [comment]
Fixed and updated nuget package available: https://www.nuget.org/packages/EntityFrameworkCore.SqlServerCompact40/1.1.0.2

**Comment by ErikEJ** [comment]
Thanks! If you use my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details
