### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by Aristarh71** [ErikEJ/EntityFramework.SqlServerCompact#503]
Is it possible to use the provider with .NET Core (netstandard2.0, netcoreapp2.0)?
If not, where i can find SqlServer Compact Edition provider for .NET Core?

**Comment by ErikEJ** [comment]
SQL Server Compact only runs on Windows x86 or x64, so there is no support for .NET Core. You can use it with .NET Standard, but it will fail on non-Windows platforms. 

If you plan to run you app on other platforms, then consider SQL Server or SQLite
