### ISSUE TITLE
Using SQL Server Compact 3.5SP1 with the Entity Framework 6.1.x designer

### ISSUE THREAD

**Issue by nasheayahu** [ErikEJ/EntityFramework.SqlServerCompact#511]
Hi ErikEJ, question, 

1. Do you have a tutorial on how to use EF 6.x designer with Ce 3.5?  
2. When trying in VS 2017, to generate database from model, it only provides Data Sources/Providers for the Server and Ce 4.0.  So I'm assuming this is not possible and I can only design it manually right?

**Comment by ErikEJ** [comment]
@nasheayahu I could not make the 3.5 Data Source work woth VS 2017, so I gave it up. You can upgrade a copy of your DB to 4.0 for the design work, and then use 3.5 at runtime

**Comment by nasheayahu** [comment]
Okay, thanks ErikEJ for your help!  Appreciate it very much...
