### ISSUE TITLE
No Entity Framework provider found for the ADO.NET provider with invariant name...

### ISSUE THREAD

**Issue by nasheayahu** [ErikEJ/EntityFramework.SqlServerCompact#512]
Hi ErikEJ,

Having trouble getting Ce 3.5 SP1 to work, how do I fix this error:

> System.InvalidOperationException occurred
  HResult=0x80131509
  Message=No Entity Framework provider found for the ADO.NET provider with invariant name 'System.Data.SqlServerCe.4.0'. Make sure the provider is registered in the 'entityFramework' section of the application config file. See http://go.microsoft.com/fwlink/?LinkId=260882 for more information.

App.config:
assemblyBinding:

> 
      <dependentAssembly>
        <assemblyIdentity name="System.Data.SqlServerCe" publicKeyToken="89845dcd8080cc91" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="3.5.1.0" />
      </dependentAssembly>

EntityFramework
>   <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlCeConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="System.Data.SqlServerCe.3.5" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="System.Data.SqlServerCe.3.5" type="System.Data.Entity.SqlServerCompact.Legacy.SqlCeProviderServices, EntityFramework.SqlServerCompact.Legacy" />
    </providers>
  </entityFramework>

DbProviderFactories:

><remove invariant="System.Data.SqlServerCe.3.5" />
      <add name="Microsoft SQL Server Compact Data Provider 3.5" invariant="System.Data.SqlServerCe.3.5" description=".NET Framework Data Provider for Microsoft SQL Server Compact" type="System.Data.SqlServerCe.SqlCeProviderFactory, System.Data.SqlServerCe, Version=3.5.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" />

Code:
`
string d = Path.Combine(dataFileDir, DbaseName);
if (!File.Exists(d))
{
	string connStr = string.Format("data source={0}", d);
	SqlCeEngine engine = new SqlCeEngine(connStr);

	engine.CreateDatabase();
	engine.Dispose();

	if (!File.Exists(d))
	{
		throw new FileNotFoundException(d);
	}
}`

Thanks!...

**Comment by ErikEJ** [comment]
I think you have a too old SQLCE 3.5 version installed. the version in DbProviders should be:

 Version=3.5.1.0,

**Comment by ErikEJ** [comment]
Installing the provider package should be sufficient. Feel free to share a repro project.

**Comment by ErikEJ** [comment]
Closing as no repro received
