### ISSUE TITLE
Union of Anonymous Type having hardwired bool property throws exception

### ISSUE THREAD

**Issue by optiks** [ErikEJ/EntityFramework.SqlServerCompact#546]
As per [GitHub issue #12623](https://github.com/aspnet/EntityFrameworkCore/issues/12623), this issue is also evident in the SQL CE provider. 

The EF Team fixed this in [GitHub issue #12280](https://github.com/aspnet/EntityFrameworkCore/issues/12280) with commit [77512c4]( https://github.com/aspnet/EntityFrameworkCore/commit/77512c451480d52f9b4e2970a8ba72d9f38c0141).

@maumur mentioned: "@ErikEJ for potential fix in SqlCE. The extensibility point has been added along with the sql server fix - it should just be a matter of implementing ApplyExplicitCastToBoolInProjectionOptimization"

**Comment by ErikEJ** [comment]
Yes, I will keep it as a reminder and update when either 2.2 or 2.1.3 is released.

**Comment by optiks** [comment]
Hi Erik, 2.1.3 is now released. Have you got any feelings on when this one will be ready? Is there anything we can do to help?

**Comment by ErikEJ** [comment]
A PR would be very welcome 😄

**Comment by ErikEJ** [comment]
@optiks I do not see 2.1.3 anywhere?? https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/

**Comment by optiks** [comment]
@ErikEK Yes, this is confusing; sorry about that. Short answer: the GitHub milestone for 2.1.3 is actually shipped as the EF Core 2.1.2 package.
 
Longer answer: ASP.NET people want to track everything on the GitHub org using the version of the ASP.NET metapackage for any given release. In addition, individual packages that do not have any changes, and do not have any changes in transitive dependencies, are not revved for a given ASP.NET metapackage release. This was the case for the ASP.NET 2.1.2 release, primarily because it was focused on some security fixes for which EF was not involved. So the 2.1.2 ASP.NET release contained EF 2.1.1. Now with the 2.1.3 release, EF does have changes, so it has been revved to 2.1.2.

**Comment by ErikEJ** [comment]
But is the fix backported to 2.1.2?

**Comment by ErikEJ** [comment]
well, in that case a PR that updates the 2.1 provider to require 2.1.2 and implements the fix would be highly appreciated

**Comment by ErikEJ** [comment]
Fixed by PR
