### ISSUE TITLE
Scaffold - Entities are not generated unless table names are manually specified with -Tables option

### ISSUE THREAD

**Issue by toomasz** [ErikEJ/EntityFramework.SqlServerCompact#567]
I tried to scaffold my SQL CE database with following command:

`Scaffold-DbContext -Connection "Data Source=C:\My\Tmp\TestSqlCe.sdf" -Provider EntityFrameworkCore.SqlServerCompact40 -OutputDir DatabaseModel/Entities -ContextDir DatabaseModel -Context MyDbContext -UseDatabaseNames -f -Verbose`

Empty DbContext was generated which is incorrect. It should generate entities for all tables in database by default as it works that way in other providers.

I can force it to generate all entities by manually specifying tables from my database with -Tables option.

Attaching test sql ce database:
[TestSqlCe.zip](https://github.com/ErikEJ/EntityFramework.SqlServerCompact/files/2727068/TestSqlCe.zip)

**Comment by ErikEJ** [comment]
I introduced a bug here https://github.com/ErikEJ/EntityFramework.SqlServerCompact/commit/28a9325134a53a0c43babaf3e88ba5e332ecc7f4 - will fix this weekend

**Comment by tscislowicz** [comment]
@ErikEJ Thanks a lot!

**Comment by ErikEJ** [comment]
Fix is to use this iso Contains:
https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs#L217

**Comment by ErikEJ** [comment]
Thanks for reporting this!
