### ISSUE TITLE
Scaffold - HasColumnType seems to be generated only for some columns

### ISSUE THREAD

**Issue by toomasz** [ErikEJ/EntityFramework.SqlServerCompact#568]
I'm not sure if this is to bo done in your library but I'm hitting a scenario where I need HasColumn adnotation for DateTime and Guid columns(and perhaps other types).
The scenario is creating SqLite database using model generated from SqlCe database.
I have PK column in source database that has uniqueidentifier type (Guids are used as Pk) and I want target column type in Sqlite to be uniqueidentifier too, instead it's generated as blob. When I add HasColumnType("uniqueidentifier") it works as expected.

Questions:
  - For which column types is HasColumnType is generated?
  - Is it possible to force HasColumnType adnotation generation when Scaffolding?

**Comment by ErikEJ** [comment]
I think the column type is only specified for "unusal" cases by design. It is not something I control. 

When is "HasColumnType" generated for you?

SQLite does not have any "uniqueidentifer" column type - in fact, it hardly has any data types: https://www.sqlite.org/datatype3.html

**Comment by toomasz** [comment]
For me it's only `HasColumnType("numeric(x, x)") and HasColumnType("ntext") ` that is generated from my SqlCe database. When i tried to scaffold same database schema from sqlite HasColumnType was generated for each column, not sure why. Im aware that SQLite has limited type system it but somehow my sqlite database opened in db browser shows this, and such 'column type' is accepted by external software that is supposed to read this database:

![obraz](https://user-images.githubusercontent.com/3065454/50699902-6d110600-1049-11e9-9b82-5524c01321ec.png)

Anyway I guess i will try to manually edit model type to add HasColumnType adnotation for all Guid and DateTime columns
