### ISSUE TITLE
Left Join Performance with Table Per Hierarchy

### ISSUE THREAD

**Issue by optiks** [ErikEJ/EntityFramework.SqlServerCompact#570]
As per https://github.com/aspnet/EntityFrameworkCore/issues/14081, performance for left-joins against Table Per Hierarchy tables is really bad.

The EF team have noted it's unlikely they'll be able to making any changes that are specific to SQL CE at this time.

Do you have any thoughts on what would be involved in modifying the EF Core SQL CE provider to generate more performant SQL?

If required, I can share some execution plans to show the impact on performance.

Cheers,

Michael

**Comment by ErikEJ** [comment]
I do not have any current plans, but I am always open for PRs! 
Do you have a repro SQL query and a test database you can share?

**Comment by optiks** [comment]
Sorry for the lack of reply. I'll try and get something together soon.

**Comment by optiks** [comment]
Closing this out. We've worked around this by creating a context which represents 'flat' entities instead of hiearchical entities, and then joining explicitly on the type discriminator.
