### ISSUE TITLE
Add support to version 4.6.x

### ISSUE THREAD

**Issue by AhmedSuror** [ErikEJ/EntityFramework.SqlServerCompact#573]
The commandline:
`Install-Package Microsoft.EntityFrameworkCore.Tools  `
is not compatible with .NET 4.6.x

when I install I get the following error:

Install-Package : Could not install package 'Microsoft.EntityFrameworkCore.Tools 2.2.2'. You are trying to 
install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not c
ontain any assembly references or content files that are compatible with that framework. For more informati
on, contact the package author.
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Tools
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.Inst 
   allPackageCommand

**Comment by ErikEJ** [comment]
Which VS version?

Can you share your csproj?

**Comment by AhmedSuror** [comment]
@ErikEJ 
[MiniFatoura.zip](https://github.com/ErikEJ/EntityFramework.SqlServerCompact/files/2926551/MiniFatoura.zip)

**Comment by ErikEJ** [comment]
But your project used EF 6 ??

```
    <Reference Include="EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL">
      <HintPath>..\packages\EntityFramework.6.2.0\lib\net45\EntityFramework.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="EntityFramework.SqlServer, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL">
      <HintPath>..\packages\EntityFramework.6.2.0\lib\net45\EntityFramework.SqlServer.dll</HintPath>
    </Reference>
    <Reference Include="EntityFramework.SqlServerCompact, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL">
      <HintPath>..\packages\EntityFramework.SqlServerCompact.6.0.1\lib\net45\EntityFramework.SqlServerCompact.dll</HintPath>
    </Reference>

```

**Comment by ErikEJ** [comment]
This is the EF Core provider, nothing to do with EF 6, and the package you are trying to install is also for EF Core

**Comment by AhmedSuror** [comment]
@ErikEJ  Thanks for reply, I've used EF provider recently and the error msg was before installing EF
