### ISSUE TITLE
Memory leaks when using Entity Framework and Sql Server Compact Edition with cached, single database connection

### ISSUE THREAD

**Issue by tstedel** [ErikEJ/EntityFramework.SqlServerCompact#577]
As per guidance, we have written our application to cache the SqlCeConnection object and to rebuild it if necessary if the connection state does not stay open. However, we have run into a memory leak.

Async operations that are passed a token will leak memory for the duration of the tokens life time. This is especially bad when there is a main application cancellation token that is passed down, because that means that one token lives as long as the app, resulting in database calls, even while properly disposing the DbContext, leak memory until we run out of memory. We have a workaround that wraps every db operation with a linked cancellation token that we dispose of.

We have created a project that demonstrates both of these issues. Uncomment the behavior in Program.cs. By default it will show the cancellation token memory leak.

[EntityFrameworkSqlCeMemoryLeak.zip](https://github.com/ErikEJ/EntityFramework.SqlServerCompact/files/3895061/EntityFrameworkSqlCeMemoryLeak.zip)

**Comment by ErikEJ** [comment]
The repo is for the SQL Server Compact EF Core provider - but I can try to help.

>> As per guidance, we have written our application to cache the SqlCeConnection object 

What guidance? That sounds wrong - if you need fast Open(), you should open a SqlCeConnection when your app starts, keep it open, and not use  it for anything, and just create new DbContext instances as needed. Make sure the connection string matches the one used by EF 100%

**Comment by tstedel** [comment]
I will continue this in the appropriate repository, sorry about that, and thank you for helping me.

**Comment by tstedel** [comment]
Sorry, I can not find the correct repository to post this in, do you have a link?

**Comment by ErikEJ** [comment]
The correct repo is EntityFramework6 - but the SQL CE provider is no longer supported. You never mentioned the source of the "guidance"?

**Comment by tstedel** [comment]
> The correct repo is EntityFramework6 - but the SQL CE provider is no longer supported. You never mentioned the source of the "guidance"?

I think that I misinterpreted guidance from you, I saw a blog post on your blog about opening a single connection, and I assumed that we were also supposed to use that single connection. A mistake on my part.

**Comment by tstedel** [comment]
[https://stackoverflow.com/questions/49388644/sqlceconnection-is-way-slower-than-sqlconnection](url)

You specify "unused" here correctly and I missed it.
