### ISSUE TITLE
Convert existing SQL Server Express app to SQL Server Compact

### ISSUE THREAD

**Issue by ArmorBearer** [ErikEJ/EntityFramework.SqlServerCompact#579]
I saw in your wiki the instructions for creating the database / model in the project.  I already have a project with a database, but it uses SQL Server Express, rather than CE.  With Express, installation / distribution issues seem to be more complex, so I wanted to try using CE.  Are there a few simple tweaks to the project that would make this conversion happen?  Or do I really need to start a new project and create the database model all over (based on the current, existing database)?

**Comment by ErikEJ** [comment]
I would use my SQL Server Compact Toolbox to migrate your SQL Express database to a SQL Compact database file, and then use EF Core Power Tools to generate a model from that database file. 

Does that make sense?

**Comment by ArmorBearer** [comment]
> I would use my SQL Server Compact Toolbox to migrate your SQL Express database to a SQL Compact database file

Do they really use a different file format between Express & Compact...?

Do you have any documentation on how to use your Toolbox?

**Comment by ErikEJ** [comment]
>> Do you have any documentation on how to use your Toolbox?

Plenty: https://github.com/ErikEJ/SqlCeToolbox/wiki
