### ISSUE TITLE
System.Security.Permissions, Version=4.0.3.0... The located assembly's manifest definition does not match the assembly reference.

### ISSUE THREAD

**Issue by davidrimshnick** [ErikEJ/EntityFramework.SqlServerCompact#581]
_Reposting from [here](https://github.com/dotnet/runtime/issues/28101#issuecomment-668340152)_

@ErikEJ I am trying your [solution ](https://github.com/dotnet/runtime/issues/28101#issuecomment-536269132) to use SQLServerCE in dotnet core but getting this error:

> FileLoadException: Could not load file or assembly 'System.Security.Permissions, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)

The project file is
[FactorPrismConsole.csproj.txt](https://github.com/ErikEJ/EntityFramework.SqlServerCompact/files/5022199/FactorPrismConsole.csproj.txt)
and it references another project file,
[FactorPrismDesktopWF.csproj.txt](https://github.com/ErikEJ/EntityFramework.SqlServerCompact/files/5022200/FactorPrismDesktopWF.csproj.txt)
also attached.

Note I tried both the files in the root folder and the x86, AMD64 folders to same result.  I also tried changine the 

`<PackageReference Include="System.Security.Permissions" Version="4.6.0" />
`
to

`<PackageReference Include="System.Security.Permissions" Version="4.6.0" />`

to no avail

Thank you very much for your help..

**Comment by ErikEJ** [comment]
Looks like you could simply share a .zip file with your test solution, then I will have a look -
