### ISSUE TITLE
UseSqlCe not found

### ISSUE THREAD

**Issue by huytnd** [ErikEJ/EntityFramework.SqlServerCompact#74]
I tried to work with EF7 & Sql Server Compact using this package, but I got this problem.
![entity_sqlce_1](https://cloud.githubusercontent.com/assets/2102905/7896492/e01ee7a0-06e5-11e5-8ceb-ca50f082be39.jpg)
I defined package dependencies in project.json
![entity_sqlce_2](https://cloud.githubusercontent.com/assets/2102905/7896503/68b4a604-06e6-11e5-80b0-d5d380539d16.jpg)

**Comment by ErikEJ** [comment]
Thanks for taking time to try out this provider!

Currently, the SqlCe package depends on the nightly builds, and has not been tested with the new project system. Look at the guide here https://github.com/ErikEJ/EntityFramework.SqlServerCompact/wiki/Using-EF7-with-SQL-Server-Compact-in-Traditional-.NET-Applications

**Comment by huytnd** [comment]
I upgraded to the latest 'nightly build' of EF7, but i got this
![entity_sqlce_3](https://cloud.githubusercontent.com/assets/2102905/7898772/298156cc-0735-11e5-9070-e8486742d244.jpg)
My updated project.json file
![entity_sqlce_4](https://cloud.githubusercontent.com/assets/2102905/7898774/37e1fe1a-0735-11e5-91fa-0050bd64c2af.jpg)

**Comment by ErikEJ** [comment]
Yes, that is expected, DbContextOptions have been renamed to EntityOptions

**Comment by huytnd** [comment]
I changed to EntityOptionsBuilder, and now I got these error.
![entity_sqlce_5](https://cloud.githubusercontent.com/assets/2102905/7898929/3417517c-073a-11e5-884c-48e3ada254ac.jpg)

**Comment by ErikEJ** [comment]
Does your project target .NET 4.5 desktop Framework, that is required for SQL CE support? SQL CE will not work with any other Framework targets.
Try to go through the sample with a .NET 4.5 console app, if you can make that work, it is probably because of your project type and or framework target

**Comment by huytnd** [comment]
I'm trying with the new ASP.NET 5 console app with DNX runtime.

**Comment by ErikEJ** [comment]
That will never work, sorry! Use SQL Server or SQLite if you must do that...
