### ISSUE TITLE
Work around for TransctionTest issue

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EntityFramework.SqlServerCompact#78]
TransactionTest - issue reported aspnet/EntityFramework#2304

**Comment by ErikEJ** [comment]
PR submitted https://github.com/aspnet/EntityFramework/pull/2311

**Comment by natemcmaster** [comment]
Fixed with e98abc9441c2d19d22d5e6f7afa84166594ad298

**Comment by ErikEJ** [comment]
Great, thanks!
