### ISSUE TITLE
Key-attribute

### ISSUE THREAD

**Issue by nicolasr75** [ErikEJ/EntityFramework.SqlServerCompact#90]
I just have tried to define a model with a composite key like this:

    class MeasuredValue
    {
        [Key, Column(Order=1)]
        public DateTime Timestamp {get; set;}
        [Key, Column(Order=2)]
        public int MeasuringPointID {get; set;}
        public double Value {get; set;}
    }

Trying to add migrations results in:
PM> add-migration initial
**The entity type 'Models.MeasuredValue' requires a key to be defined.**

Is the Key-Attribute already supposed to work? Looks like I can only use ID as the name of a Key-Property.
With the EF6 Sql Compact Provider this works. I have attached a screenshot that shows how it is displayed in SqlCeToolbox. (Sorry for any misunderstanding on my side, I'm quite a beginner with EF)
![ef6](https://cloud.githubusercontent.com/assets/3595142/8033320/9eb9970c-0ddd-11e5-9d1f-8637c98f4bb7.png)

**Comment by ErikEJ** [comment]
Thanks for taking your time to try out this provider. Currently, attributes are not supported. 
You can use the fluent api like this, hope it works for your scenario:
   
      modelBuilder
                .Entity<MeasuredValue>()
                .Key(m => new { m.Timestamp, m.MeasuringPointId});

**Comment by nicolasr75** [comment]
Thanks, that works perfectly! By the way, many thanks for your great SqlCeToolbox too. I guess some peaple (including me) would be lost without it!

**Comment by ErikEJ** [comment]
You are welcome, and thanks Again for taking time to try out this pre-release library
